"use client"
import { AppShell, MantineProvider, MantineTheme } from '@mantine/core'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const spacing = { xs: "5px", sm: "18px", md: "40px", lg: "60px", xl: "100px" };
  const generateTheme = (theme: MantineTheme) => {
    return ({
      ".mantine-List-itemWrapper": {
        display: "block"
      }
    })
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={{globalStyles: generateTheme, spacing}}>
          <AppShell>
            {children}
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  )
}